Mpi auth
hicsail/damplab-backend pull request #36
Opened 2024-09-13 11:52 UTC by chris-krenz

# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist

- [ ] This PR can be reviewed in under 30 minutes
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned reviewers to this PR.

2024-09-13 14:12 UTC, cbolles requested changes
It looks good, I added some suggestions to keep the code base cohesive

2024-09-13 14:12 UTC, cbolles commented on src/mpi/mpi.service.ts
> +        console.log('user ', user, ' has valid token');
Best to avoid having left over `console.log`s

2024-09-13 14:12 UTC, cbolles commented on src/mpi/mpi.service.ts
> +      return new BadRequestException('No token found, log in to MPI first');
Ideally this is an `Unauthroized` exception

2024-09-13 14:12 UTC, cbolles commented on src/mpi/mpi.service.ts
> +    const sequences = await axios.get('http://localhost:5000/sequences', {
The URL should probably be a config value

2024-09-13 14:12 UTC, cbolles commented on src/mpi/mpi.service.ts
> +      return new BadRequestException('No token found, log in to MPI first');
Another `Unauthorized` exception usage

2024-11-19 15:44 UTC, chris-krenz commented on src/mpi/mpi.controller.ts
> +@Controller('mpi')
I suppose just to reflect the MPI backend

2025-03-28 17:42 UTC, closed without merging